MyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rafih/admoon/defender/',include('defender.urls')),
    path('rafih/admoon/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('account.urls')),
    path('',include('cart.urls')),
    path('items/',include("items.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .forms import LoginForm
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/topup/',views.topup,name='topup'),
    path('profile/settings/',views.settings,name='settings'),
    path('profile/vendor/',views.vendor_menu,name='vendor'),
    path('profile/settingprofile/',views.settingprofile,name='settingprofile'),
    path('profile/<str:user>',views.another_profile,name='another_profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/',views.cart_view,name='cart_view'),
    path('cart/checkout/',views.checkout_view,name='checkout'),
    path('cart/confirmcheckout/',views.checkout,name='confirmcheckout'),
    path('history/',views.history,name='history'),
    path('cart/checkout/<int:pk>/<int:price>/',views.add_pk,name='add_checkout')
]

items/urls.py
from django.urls import path, include
from . import views

app_name = "items"

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('new/',views.new,name='new'),
]

items/models.py
from django.db import models

# Models database in core/models.py

items/forms.py
from django import forms
from core.models import Produk

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItem(forms.ModelForm):
    class Meta:
        model = Produk
        fields = ('nama_barang','gambar','deskripsi','harga','jumlah')
        widgets = {
            'nama_barang': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'gambar': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'deskripsi': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'harga': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'harga': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditItem(forms.ModelForm):
    class Meta:
        model = Produk
        fields = ('nama_barang','gambar','deskripsi','harga','jumlah','is_sold')
        widgets = {
            'nama_barang': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'gambar': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'deskripsi': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'harga': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'harga': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import NewItem, EditItem
from core.models import Produk
from cart.views import add_pk

def detail(request,pk):
    produk = get_object_or_404(Produk,pk=pk)
    q = produk.created_by

    if request.method == "POST":
        quantity2 = request.POST.get('jumlah')

        quantity = int(quantity2)
        return add_pk(request,pk=pk,price=produk.harga,quantity=quantity)

    return render(request, 'items/detail.html',{
        'produk': produk,
        'q':q,
    })

@login_required
def new(request):
    if request.method == "POST":
        form = NewItem(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
        
            return redirect('items:detail', pk=item.id)

    else:
        form = NewItem()

    return render(request, 'items/new.html',{
        'form':form,
        'title':"New Item"
    })

@login_required
def edit(request,pk):
    produk = get_object_or_404(Produk, pk=pk, created_by=request.user)
    if request.method == "POST":
        form = EditItem(request.POST, request.FILES, instance=produk)

        if form.is_valid():
            form.save()

            return redirect('items:detail', pk=produk.id)

    else:
        form = EditItem(instance=produk)

    return render(request, 'items/edit.html', {
        'form': form,
        'item': produk.id,
    })

@login_required
def delete(request,pk):
    produk = get_object_or_404(Produk, pk=pk, created_by=request.user)
    produk.delete()

    return redirect('core:index')

items/templates/items/detail.html
{% extends 'core/base.html'%}

{% block title %}{{ item.name }}{% endblock %}

{%block h1%}
    <h1>{{produk.nama_barang}}</h1>
{%endblock%}

{%block content%}
<div class="container mx-auto py-8">
    <div class="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-md">
        <div class="grid grid-cols-1 md:grid-cols-2">
            <div class="w-full">
                <img src="{{produk.gambar.url}}" alt="Nama Barang" class="w-full h-auto rounded-lg">
            </div>
            <div class="w-full p-4">
                <h2 class="text-2xl font-semibold">{{produk.nama_barang}}</h2>
                <p class="text-gray-600">{{produk.deskripsi}}</p>
                <div class="mt-4">
                    <p class="text-xl font-semibold">Price: {{produk.harga}}</p>
                    <p class="text-xl font-semibold">Quantity: {{produk.jumlah}}</p>
                    <div class="mt-4">
                        <p class="text-gray-600">Selled by: <a href="{% url 'account:another_profile' produk.created_by %}" class="text-blue-500">{{ produk.created_by }}</a></p>
                    </div>
                </div>
            </div>
            <div class="w-full p-4">
                <div class="flex flex-col md:flex-row justify-between items-center">
                    {% if request.user == produk.created_by %}
                    <a href="{%url 'items:delete' produk.id%}" class="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 mb-2 md:mb-0 md:mr-2 w-full md:w-auto text-center md:text-left">Delete</a>
                    <a href="{%url 'items:edit' produk.id%}" class="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 w-full md:w-auto text-center md:text-left">Edit</a>
                    {% else %}
                    <form method="post" action="{% url 'items:detail' produk.id %}">
                        {% csrf_token %}
                        <label for="jumlah">Quantity:</label>
                        <input type="number" id="jumlahBeli" name="jumlah" min="1" max="{{ produk.jumlah }}"value="1">
                        {%if produk.jumlah != 0%}
                        <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-600 w-full md:w-auto text-center md:text-left">Checkout</button>
                        {%else%}
                        <div>
                            <button disabled class="inline-block px-8 py-4 rounded-xl bg-gray-500 cursor-not-allowed">Checkout</button>
                        </div>
                        {%endif%}
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="beliSekarangPopup" class="hidden fixed top-0 left-0 w-full h-full bg-gray-800 bg-opacity-50 flex items-center justify-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </form>
</div>
{%endblock%}


items/templates/items/edit.html
{%extends 'core/base.html'%}

{%block title%}Edit Item{%endblock%}

{% block content %}
<h1 class="mb-6 text-3xl">Edit Item</h1>

<form method="post" action="{% url 'items:edit' item %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-gray">Submit</button>

</form>
{% endblock %}

items/templates/items/new.html
{% extends 'core/base.html' %}

{%block title%}{{ title }}{%endblock%}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-gray">Submit</button>

{% endblock %}