MyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rafih/admoon/defender/',include('defender.urls')),
    path('rafih/admoon/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('account.urls')),
    path('',include('cart.urls')),
    path('items/',include("items.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .forms import LoginForm
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/topup/',views.topup,name='topup'),
    path('profile/settings/',views.settings,name='settings'),
    path('profile/vendor/',views.vendor_menu,name='vendor'),
    path('profile/settingprofile/',views.settingprofile,name='settingprofile'),
    path('profile/<str:user>',views.another_profile,name='another_profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/',views.cart_view,name='cart_view'),
    path('cart/checkout/',views.checkout_view,name='checkout'),
    path('cart/confirmcheckout/',views.checkout,name='confirmcheckout'),
    path('history/',views.history,name='history'),
    path('cart/checkout/<int:pk>/<int:price>/',views.add_pk,name='add_checkout')
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User

from core.models import Produk

class Purchasehistory(models.Model):
    product_name = models.ForeignKey(Produk, related_name='product_name', on_delete=models.CASCADE, db_column='product_name')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    quantity = models.IntegerField(blank=True)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    total_paid = models.IntegerField(blank=True)
    is_paid = models.BooleanField(default=True)
    created_by = models.ForeignKey(User,related_name='orders',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'purchasehistory'

    def __str__(self):
        return f"{str(self.created_by)},{str(self.product_name)}"

cart/forms.py
from django import forms
from .models import Purchasehistory

CLASS_INPUT = "w-full p-5 rounded-xl"

class Purchaseform(forms.ModelForm):
    class Meta:
        model = Purchasehistory
        fields = ("first_name","last_name","address","zipcode","city")
        widgets = {
            "first_name": forms.TextInput(attrs={
                "class": "w-full p-5 rounded-xl"
            }),
            "last_name": forms.TextInput(attrs={
                "class": CLASS_INPUT
            }),
            "address": forms.TextInput(attrs={
                "class": CLASS_INPUT
            }),
            "zipcode": forms.TextInput(attrs={
                "class": CLASS_INPUT
            }),
            "city": forms.TextInput(attrs={
                "class": CLASS_INPUT
            }),
        }

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from core.models import Produk
from account.models import UserProfile
from .forms import Purchaseform
from .cart import Cart
from .models import Purchasehistory

@login_required
def cart_view(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html',{
        'cart': cart
    })

@login_required
def add_pk(request,pk,price,quantity):
    request.session['selected_product'] = {"pk":pk,'price':price,'quantity':quantity,'total':int(price) * int(quantity)}
    return redirect('cart:checkout')

@login_required
def checkout_view(request):
    dompet = UserProfile.objects.get(username_acc = request.user)
    selected_product = request.session.get('selected_product')
    total = selected_product.get('total')
    quantity = selected_product.get('quantity')
    pk = selected_product.get('pk')
    produk_instance = Produk.objects.get(pk=pk)
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        address = request.POST.get('address')
        zipcode = request.POST.get('address')
        city = request.POST.get('city')
        
        new_history = Purchasehistory.objects.create(product_name=produk_instance,first_name=first_name,last_name=last_name,quantity=quantity,address=address,zipcode=zipcode,city=city,total_paid=total,created_by=request.user)

        if new_history:
            return redirect('cart:confirmcheckout')
        
    return render(request, 'cart/checkoutpage.html',{
        'total': total,
        'dompet': dompet
    })

@login_required
def checkout(request):
    selected_product = request.session.get('selected_product')
    dompet = UserProfile.objects.get(username_acc = request.user)
    total = selected_product.get('total')
    pk = selected_product.get('pk')
    quantity = selected_product.get('quantity')
    product = Produk.objects.get(pk=pk)

    if selected_product:
        if dompet.saldo >= total and quantity <= product.jumlah:
            dompet.saldo -= int(total)
            product.jumlah -= int(quantity)
            product.save()
            dompet.save()
            return redirect('cart:history')

@login_required
def history(request):
    history = Purchasehistory.objects.filter(created_by=request.user)
    return render(request, 'history/history.html',{
        'history':history,
    })
        

cart/templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="products w-full lg:w-3/4">
        {% for item in cart %}
            <div class="product mb-6 flex pr-6">
                <a href="#" class="w-1/4">
                    <img class="hover:shadow-lg rounded-xl" src="{{ item.product.gambar.url }}">
                </a>

                <div class="w-3/4 pl-6">
                    <div class="flex justify-between">
                        <a href="#" class="text-lg">{{ item.product.nama_barang }}</a>

                        <span class="mb-6 pt-1 text-gray-400">${{ item.total_price }}</span>
                    </div>

                    <hr>

                    <div class="quantity mt-6 flex items-center space-x-4">
                        <a href="#" class="p-3 bg-gray-100">-</a>
                        <span>{{ item.quantity }}</span>
                        <a href="#" class="p-3 bg-gray-100">+</a>
                        <a href="{%url 'cart:checkout' item.id %}" class="inline-block px-8 py-4 rounded-xl bg-blue-500 hover:bg-purple-700 text-white">Checkout</a>
                    </div>
                </div>
                
            </div>
        {% endfor %}
    </div>

    <div class="summary w-full w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h2 class="uppercase text-lg mb-5">Summary</h2>

        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Total All Item</span>
            <span>${{ cart.get_total_cost }}</span>
        </div>

    </div>
</div>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="products w-full lg:w-3/4">
        <h1 class="mb-5 text-3xl">Checkout</h1>
        
        <div class="w-full pr-6">
            <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                <h2 class="mb-5 uppercase text-lg">Shipping information</h2>
                <form method="post" action="{%url 'cart:checkout'%}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-4">
                    <label class="inline-block mb-2">First Name</label>
                    {{form.first_name}}
                </div>
                
                <div class="mb-4">
                    <label class="inline-block mb-2">Last Name</label>
                    {{form.last_name}}
                </div>
                
                <div class="mb-4">
                    <label class="inline-block mb-2">Address</label>
                    {{form.address}}
                </div>

                <div class="flex space-x-6">
                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">Zip code</label>
                        {{form.zipcode}}
                    </div>

                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">City/Place</label>
                        {{form.zipcode}}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="summary w-full w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h2 class="uppercase text-lg mb-5">Summary</h2>
        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Total</span>
            <span>${{ total }}</span>
        </div>
        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Balance in account</span>
            <span>${{ dompet.saldo }}</span>
        </div>
        {%if total < dompet.saldo%}
        <button type="submit" class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Confirm checkout</button>
    </form>
        {%else%}
        <div>
            <button disabled class="inline-block px-8 py-4 rounded-xl bg-gray-500 cursor-not-allowed">Confirm checkout</button>
        </div>
        <div class="mt-2 text-red-500">
            Saldo kurang, harap melakukan
            <a href="{%url 'account:topup'%}" class="text-blue-500">topup</a>.
        </div>
        {%endif%}
    </div>
</div>
{% endblock %}

cart/templates/cart/checkoutpage.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="products w-full lg:w-3/4">
        <h1 class="mb-5 text-3xl">Checkout</h1>
        
        <div class="w-full pr-6">
            <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                <h2 class="mb-5 uppercase text-lg">Shipping information</h2>
                <form method="post" action="{%url 'cart:checkout'%}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-4">
                    <label class="inline-block mb-2" for="first_name">First Name</label>
                    <input type="text" name="first_name" class="w-full p-5 rounded-xl" required>
                </div>
                
                <div class="mb-4">
                    <label class="inline-block mb-2" for="last_name">Last Name</label>
                    <input type="text" name="last_name" class="w-full p-5 rounded-xl" required>
                </div>
                
                <div class="mb-4">
                    <label class="inline-block mb-2" for="address">Address</label>
                    <input type="text" name="address" class="w-full p-5 rounded-xl" required>
                </div>
                
                <div class="flex space-x-6">
                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2" for="zipcode">Zip code</label>
                        <input type="number" name="zipcode" class="w-full p-5 rounded-xl" required>
                    </div>
                
                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2" for="city">City/Place</label>
                        <input type="text" name="city" class="w-full p-5 rounded-xl" required>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="summary w-full w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h2 class="uppercase text-lg mb-5">Summary</h2>
        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Total</span>
            <span>${{ total }}</span>
        </div>
        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Balance in account</span>
            <span>${{ dompet.saldo }}</span>
        </div>
        {%if total < dompet.saldo%}
        <button type="submit" class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Confirm checkout</button>
    </form>
        {%else%}
        <div>
            <button disabled class="inline-block px-8 py-4 rounded-xl bg-gray-500 cursor-not-allowed">Confirm checkout</button>
        </div>
        <div class="mt-2 text-red-500">
            Saldo kurang, harap melakukan
            <a href="{%url 'account:topup'%}" class="text-blue-500">topup</a>.
        </div>
        {%endif%}
    </div>
</div>
{% endblock %}