MyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rafih/admoon/defender/',include('defender.urls')),
    path('rafih/admoon/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('account.urls')),
    path('',include('cart.urls')),
    path('items/',include("items.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .forms import LoginForm
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='account/login.html',authentication_form=LoginForm), name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/topup/',views.topup,name='topup'),
    path('profile/settings/',views.settings,name='settings'),
    path('profile/vendor/',views.vendor_menu,name='vendor'),
    path('profile/settingprofile/',views.settingprofile,name='settingprofile'),
    path('profile/<str:user>',views.another_profile,name='another_profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart/',views.cart_view,name='cart_view'),
    path('cart/checkout/',views.checkout_view,name='checkout'),
    path('cart/confirmcheckout/',views.checkout,name='confirmcheckout'),
    path('history/',views.history,name='history'),
    path('cart/checkout/<int:pk>/<int:price>/',views.add_pk,name='add_checkout')
]

core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('',views.index, name='index'),
    path('aboutme',views.aboutme,name='aboutme')
]

items/urls.py
from django.urls import path, include
from . import views

app_name = "items"

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('new/',views.new,name='new'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Keranjang(models.Model):
    id_keranjang = models.OneToOneField('Produk', models.DO_NOTHING, db_column='id_keranjang', primary_key=True)
    jumlah = models.PositiveIntegerField()

    class Meta:
        managed = False
        db_table = 'keranjang'

class Produk(models.Model):
    nama_barang = models.CharField(max_length=100)
    gambar = models.ImageField(upload_to="item_images", null=True, blank=True)
    deskripsi = models.TextField(blank=True,null=True)
    harga = models.PositiveIntegerField()
    jumlah = models.PositiveIntegerField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'produk'

    def __str__(self):
        return self.nama_barang

core/views.py
from django.shortcuts import render
from .models import Produk, Keranjang

def index(request):
    produk = Produk.objects.filter(is_sold=False).exclude(jumlah=0)
    return render(request, 'core/index.html', {
        'produk': produk,
    })

def aboutme(request):
    return render(request,'core/aboutme.html')

core/templates/core/aboutme.html
{%extends 'core/base.html'%}

{%block title%}About Me{%endblock%}

{%block content%}
<body class="bg-gray-100 font-sans">

    <div class="container mx-auto p-8">
        <h1 class="text-4xl font-bold mb-6">About Me</h1>

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name:</label>
            <p class="text-gray-800">Muhammad Rafihul Akhiroh</p>
        </div>


        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email:</label>
            <p class="text-gray-800">rafihul2905@gmail.com</p>
        </div>
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="creation-date">Website Creation Date(First Commit):</label>
            <p class="text-gray-800">October 17, 2023</p>
        </div>

        <div class="mb-4">
            <a href="https://instagram.com/rfihull?igshid=b3V0MG8xZ2Rvd3g0">
                <svg class="h-8 w-8 text-black-500"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" /></svg>
            </a>
        </div>
    </div>

</body>
{%endblock%}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        /* Tambahkan CSS untuk footer */
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        .container {
            flex: 1;
        }
        #errorText {
            display: none;
            color: red;
        }
    </style>
</head>
<body class="bg-white-100">
    <header class="bg-blue-500 text-white py-4 flex justify-between items-center">
        <div class="container mx-auto md:flex md:items-center ml-auto space-x-4 flex-grow">
            <div class="text-center flex items-center">
                {% if user.is_authenticated %}
                <a href="{% url 'account:profile' %}" class="text-white hover:text-blue-500">Account</a>
                {% else %}
                <a href="{% url 'account:login' %}" class="text-white hover:text-blue-500">Login</a>
                {% endif %}
            </div>
        </div>
    </header>
    
    <nav class="bg-gray-800 text-white py-2">
        <div class="container mx-auto">
            <ul class="flex justify-center space-x-4">
                <li><a href="{% url 'core:index' %}" class="hover:text-blue-500">Home</a></li>
                <li><a href="{%url 'core:aboutme'%}" class="hover:text-blue-500">About</a></li>
                <li><a href="{% url 'items:new' %}" class="hover:text-blue-500">Add Item</a></li>
            </ul>
        </div>
    </nav>
    <div class="container mx-auto py-8">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="bg-gray-800 text-white text-center py-4">
        &copy; Backend Web
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
    {% for item in produk %}
    <div class="bg-white p-4 shadow-md">
        <a href="{% url 'items:detail' item.id %}">
            <img src="{{ item.gambar.url }}" alt="{{ item.nama_barang }}" class="mx-auto mb-4">
        </a>
        <h2 class="text-xl font-semibold">{{ item.nama_barang }}</h2>
        <p class="text-gray-600">Price: {{ item.harga }}</p>
        <p class="text-gray-600">quantity: {{ item.jumlah }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}
